### PR TITLE
Add or update codes in open codelists

### LINKED ISSUE #405: itemClassificationScheme: Add 'CUCOP' code
Used in Mexico. See https://sites.google.com/site/cnetcucop/

### LINKED ISSUE #557: partyRole: Add 'interestedParty' code
From @dwasyl:

> `interestedParty` is a perfect format of what I’m looking for with the register concept. I see where it would be useful in the P3 (public private partnerships) add-on, although I would suggest that it is a decent code to bump up to the main schema since it could easily apply to any tendering process or separate out on it's own. For me it could be linked to the question/answer data model as well.

This code exists in the PPP profile with the following definition:

> A party which has expressed an interest in the project, for example by purchasing tender documents or submitted clarification questions, but has not yet formally submitted a bid.

### LINKED ISSUE #619: documentType: Add 'priorInformationNotice' code
We got a request to add 'priorInformationNotice' to the open ```documentType``` codelist, as prior information notice is one of the most common forms in procurement process.

### PR DESCRIPTION
**Pull request by jpmckinney**
Creating PR so that this branch and these commits are better surfaced on GitHub.

closes #619, closes #405, closes #557

### CODE REVIEW

**Comment by jpmckinney** [comment]
I changed 'priorInformationNotice' to 'plannedProcurementNotice' following to the discussion in #619. I changed the suggested description from:

> A notice issued by the procuring authority regarding their plans for a future procurement. In some circumstances the notice may also act as an invitation to bid. Also known as a Prior Information Notice.

to:

> A formal notice regarding plans for future procurement, also known as a prior information notice. The notice may be used as a tender notice.

I prefer "plans for future procurement" to "future procurement plans", because "procurement plan" can have a distinct meaning and is often itself interpreted as a plan for future procurement, such that "a notice regarding their future procurement plans" (GPA text) could be interpreted as "a notice regarding future plans for future procurement", which is not the intended meaning. The term "plans for future procurement" is in use, based on a quick web search.

**Comment by jpmckinney** [comment]
Need to check these updates against the [OCDS](https://docs.google.com/spreadsheets/d/1WGH9_mHYuF4JbK2tdyeckqsmj8v4HrRqDOEbKQ7CI4A/edit#gid=0) and [e-Procurement Ontology](https://docs.google.com/spreadsheets/d/1zw9aR8GDIDUiTDtSznMxDlZQEAGb8uNzib9KBZLf5yE/edit#gid=0) glossaries.

**Update:** The updated codes from #687 and #714 have been compared. For the others above, the glossaries have no term corresponding to 'interestedParty' or 'environmentalImpact'. 'CUCOP' is not applicable, and 'tender' was reverted above. plannedProcurementNotice has no term in OCDS, so the only remaining consideration is the definition of "Prior information notice" in ePO:

> Notice which sets out the contracting authority's purchasing intentions. It is used by contracting authorities to provide suppliers with information about a procurement process.

This PR's current description is:

> A formal notice regarding plans for future procurement, also known as a prior information notice. The notice may be used as a tender notice.

which is based on text from GPA (with relevant portions for re-use in bold):

> **Procuring entities** are encouraged to **publish** in the appropriate paper or electronic medium listed in Appendix III as early as possible in each fiscal year **a notice regarding their future procurement plans** (hereinafter referred to as “notice of planned procurement”).  The notice of planned procurement should include the subject-matter of the procurement and the planned date of the publication of the notice of intended procurement.
> A procuring entity covered under Annex 2 or 3 **may use a notice of planned procurement as a notice of intended procurement** provided that the notice of planned procurement includes as much of the information referred to in paragraph 2 as is available to the entity and **a statement that interested suppliers should express their interest in the procurement to the procuring entity**.

Regarding the ePO definition: The second clause is somewhat obvious, and the first clause is functionally equivalent to the GPA-derived description.

However, I see some additional relevant portions of the GPA text, for which I'll make a commit.

**Review by duncandewhurst — APPROVED** [review]
This PR looks good. The proposed description for 'interestedParty` from https://github.com/open-contracting/standard/issues/557#issuecomment-475322471 could also be added.

**Comment by jpmckinney** [comment]
I've made the updates to interestedParty to CUCOP – will merge once tests complete.

**Pull request merged**
