### PR TITLE
Add personal identifiers example

### LINKED ISSUE #801: Personal identifiers
In some countries, as in Honduras and Colombia, some of their tenderers and suppliers have as identifier the ID number, passport or residence card number. Currently the standard documentation says that:

"Organization identifiers should be drawn from an existing organization identifier list. The scheme field is used to indicate the list or register from which the identifier is drawn. This value should be drawn from the Organization Identifier Scheme codelist." [1]

And:

"The Organization Identifier Scheme currently uses the codes from org-id.guide." [2]

But the personal identifiers cannot be included in the org-id.guide site, because it only publishes organization identifiers, not personal ones.

How they should publish these identifiers? 

Refs: [1] http://standard.open-contracting.org/latest/en/schema/reference/#identifier
[2] http://standard.open-contracting.org/latest/en/schema/codelists/#organization-identifier-scheme

Honduras Examples:

- ID number_ http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=OAAAADIAAAAwAAAAMQAAADcAAAA%3d-344y8BF%2fMHE%3d
- passport:  http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADcAAAA3AAAAMgAAADkAAAA%3d-2Lgi74%2fBkcQ%3d
- residence card number: http://sicc.honducompras.gob.hn/HC/Contratos/ContratoDD.aspx?Id=NwAAADYAAAA1AAAANQAAADMAAAA%3d-OcYuYrpmGFs%3d

### PR DESCRIPTION
**Pull request by yolile**
closes #801

### CODE REVIEW

**Comment by jpmckinney** [comment]
@yolile Please request a review by an analyst, first.

**Review by mrshll1001 — APPROVED** [review]
All good.

**Review by jpmckinney — CHANGES_REQUESTED** [review]
There are several things I'd like to change:

* Make it clear that an individual (a natural person) should only appear in the parties array in the case that the individual is a supplier (often referred to as a "sole trader" or "self-employed individual").
* Use "uppercase ISO 3166-1 alpha-3 country code" instead of "ISO 3-digit country code" (digits are 0-9…).
* Run a spelling/grammar checker.
* Don't line wrap.

**Comment by yolile** [comment]
@jpmckinney ok and about 
> Use "uppercase ISO 3166-1 alpha-3 country code" instead of "ISO 3-digit country code" (digits are 0-9…).

That paragraph is textually cited from http://standard.openownership.org/en/schema-beta-2/schema/guidance/identifiers.html?#shared-identifiers

**Comment by jpmckinney** [comment]
Yes, I'm saying their paragraph is bad. Ours should be better :)

**Comment by jpmckinney** [comment]
Requesting Duncan's review as there are grammatical issues.

**Review by duncandewhurst — APPROVED** [review]

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
