### PR TITLE
Clarify the instruction for setting the release.date field

### LINKED ISSUE #854: Clarify release.date field description
One publisher was updating the release date for all releases relating to a contracting process whenever anything changed. Other publishers have used it for the date when they generated the release, not when the process was made or first published in their local system. The current description is ambiguous, allowing for the above behaviors:

> The date this information was first released, or published

The field value should be the date on which the information contained in the release was first created or published in any system.

Related #848 and #849

### PR DESCRIPTION
**Pull request by yolile**
closes #854

### CODE REVIEW

**Comment by jpmckinney** [comment]
I think you need to run `util/make_dereferenced_release_schema.py` whenever changing the release schema, otherwise tests will fail.

As it happens, it looks like a GitHub rate-limiting issue also caused the tests to fail (never saw that before).

**Comment by yolile** [comment]
@jpmckinney done

**Comment by jpmckinney** [comment]
Beautiful, tests pass (at least sometimes!).

**Comment by jpmckinney** [comment]
I forgot to ask: Can you add a bullet point to the changelog under the Schema heading?

**Pull request merged**
