### PR TITLE
1.0.2 Release

### PR DESCRIPTION
**Pull request by Bjwebb**
## Changes

From https://github.com/open-contracting/standard/blob/1.0.2/changelog.md#102---2016-tbc

### Fixed

- Added titles to all fields in the documentation (#362)
- Missing field ```procurementMethodDetails``` added to schema (#221)
- Typo fix in releaseTag (#391)
- Fixing links to Fiscal Data Package (#271)
- Description for ```numberOfTenderers``` (#314)
- Fixed definition of ```changes``` (#244)
- Updated documentation to refer to 'Object' not 'Reference' for fields (#228)

### Tidy up

- Removed the old Spanish documentation translations folders from ```standard/docs/es```
- Added CSV download links for registered OCIDs, and publication levels
- Updated publication levels spreadsheet to reflect version 1.0.2

## Deployment steps

From https://github.com/open-contracting/standard/edit/1.0-dev/DEPLOYMENT.md

Before merge:
- [x] [Push translations to transifex if any text has changed](https://github.com/open-contracting/standard#translations)
- [x] [Pull completed translations from transifex](https://github.com/open-contracting/standard#translations)
- [x] Set up a dev instance of Cove using the new schema, and run tests against it

After merge:
- [x] Copy the files from dev to live following the instructions at the top of https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/ocds-docs-live.sls
- [x] Create x__y__z schema folder - https://github.com/OpenDataServices/opendataservices-deploy/blob/master/salt/ocds-docs-live.sls#L25
- [x] Update live Cove to use the new schema

### CODE REVIEW

**Comment by Bjwebb** [comment]
Cove looks to be happy with the new schema https://travis-ci.org/OpenDataServices/cove/builds/175131629

**Comment by Bjwebb** [comment]
Spanish translation updated with current transifex - http://standard.open-contracting.org/1.0.2/es/getting_started/use_cases/

I think this is now ready to merge.

**Comment by timgdavies** [comment]
Reviewed and looks good to go.

**Comment by Bjwebb** [comment]
This is now live at http://standard.open-contracting.org/ and permalinks to the 1.0.2 schema at http://standard.open-contracting.org/schema/1__0__2/

**Pull request merged**
