### PR TITLE
map: Move linked standards to map

### LINKED ISSUE #1275: Move "Linked Standards" section to Map
Currently, the "Linked Standard" section is under [Guidance->Map->Extension](https://standard.open-contracting.org/latest/en/guidance/map/extensions/#linked-standards), however, it could have its own section under Map, and we should add an admonition on the extensions page to reference this new page

### PR DESCRIPTION
**Pull request by yolile**
closes #1275

### CODE REVIEW

**Comment by jpmckinney** [comment]
@yolile Is this ready for review?

**Comment by jpmckinney** [comment]
Hmm, this is a lot of content for the Map page itself (especially with more linked standards like BODS coming). Should we instead have a new "linked standards" page? Then, on the Map page, we can have under a Linked standards heading:

Not all information that is related to a contracting process belongs in OCDS. For example, a company's annual filings and incorporation status are typically managed in a company registry, outside the lifecycle of a contracting process.

For guidance on integrating your OCDS data with these related datasets, refer to [Linked standards]().

**Comment by yolile** [comment]
> Should we instead have a new "linked standards" page?

That was my first approach but I wasn't sure if it was the best, I will change it to a new page then

**Comment by yolile** [comment]
done @jpmckinney

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
