### PR TITLE
Pre qualification example

### PR DESCRIPTION
**Pull request by duncandewhurst**

### CODE REVIEW

**Comment by duncandewhurst** [comment]
@jpmckinney did you want someone else to review this first?

**Comment by jpmckinney** [comment]
I'm assuming not much has changed since Yohanna's review of the Google document, so I can review.

**Comment by duncandewhurst** [comment]
@jpmckinney fyi - I'm working on some copy edits to this worked example. I'll let you know when it's ready for review.

**Comment by jpmckinney** [comment]
@duncandewhurst Okay, just request a review when ready.

**Pull request merged**
