### PR TITLE
Clarify contracting process, record and ocid, define planning process (866)

### LINKED ISSUE #866: Clarify definition of contracting process
## Problem

A contracting process is described in terms of an 'initiation process' on http://standard.open-contracting.org/latest/en/getting_started/contracting_process/#defining-a-contracting-process:

> All the planning, tendering information, awards, contracts and contract implementation information related to a single initiation process.

> An initiation process might be a tender, a direct contract award, or a call to award a concession.

However, we never define what an 'initiation process' is, which makes the definition ambiguous. 

The only [example](http://standard.open-contracting.org/latest/en/implementation/related_processes/) given for multiple initiations is:

> for example, when a framework is setup, and then mini-competitions are used for purchases from the framework

This was introduced in #439 (related to #310) on April 24, 2017, after the peer review for 1.1, and the changes regarding the description of 'initiation process' were not mentioned in the [update](https://docs.google.com/spreadsheets/d/1x1WG2-7E134OJ6ceWV3Sn5okhn4ARIeVYI8D0ALBLHA/edit#gid=92056586) to peer reviewers. As such, we should treat the mini-competitions example as non-normative guidance.

The 'tender' code in the `initiationType` codelist would also need correction of its description. #821

## Background

In the BPMN for a restricted procedure shared by EBRD, the process could be said to be 'initiated' by the publication of a contract notice (tender notice), after which there is 'supplier qualification' (pre-qualification), 'tendering' (submitting bids, etc.), and so on. (The BPMN for an open procedure is similar, but without a supplier qualification stage.)

In the EU, the same notice is used whether there is a supplier qualification stage or not (which is why the phrase "tenders or requests to participate" is used).

In the EU, the contract establishing a framework agreement and each contract resulting from a framework agreement are considered to be the same procedure. https://github.com/eForms/eForms/issues/221#issuecomment-466436451

## Discussion

For a restricted procedure, I think it's correct to say there is only one initiation process (publication of a contract notice), not two (pre-qualification and tendering). This agrees with [this comment](https://github.com/open-contracting/standard/issues/371#issuecomment-292117603) from the peer review, and disagrees with this [later interpretation](https://github.com/open-contracting-extensions/ocds_qualification_extension/commit/9fb9d1ed8119dab8bed95fb450930aa043a762b4) in the [qualification extension](https://extensions.open-contracting.org/en/extensions/qualification/master/).

For a framework agreement, the same comment from the peer review indicates that all contracts resulting from a framework agreement are part of the same procedure/process that established the framework agreement. Further discussion can be pursued in #440 

## Proposal

* [x] Improve the definition of a contracting process, to be clearer about initiation processes (or substitute that term with an equivalent)
* [x] Remove the warnings from the qualification extension

### LINKED ISSUE #1159: Worked example: Move discussion of contracting process out of unsuccessful tenders
The worked example was merged in #1007 based on [this outline](https://docs.google.com/document/d/1bIOMCC1sQjrz2UO5bkc2PcHtTaDA2C1W7jeXRRqGjfE/edit).

However, it spends the first half explaining what a contracting process is.

This content should be moved/removed, since #866 will define a contracting process.

### PR DESCRIPTION
**Pull request by JachymHercher**
closes #866 (except the two new tickets to be opened on the basis of the last paragraph of https://github.com/open-contracting/standard/issues/866#issuecomment-754939713)

closes #1159 

together with #1208, closes https://github.com/open-contracting/standard/issues/903

### CODE REVIEW

**Comment by jpmckinney** [comment]
@JachymHercher Is this still draft?

**Comment by jpmckinney** [comment]
Hi @JachymHercher, this PR now conflicts quite severely with other changes you (and maybe others) made in other PRs. My suggestion would be to:

1. Get a clean version of the 1.2-dev branch, e.g.

        git checkout 1.2-dev
        git pull --rebase

1. Start a new branch
2. Look at this PR's changes at https://github.com/open-contracting/standard/pull/1216/files and/or download the PR's changes from https://patch-diff.githubusercontent.com/raw/open-contracting/standard/pull/1216.patch
3. Replicate the desired changes to the new branch. You can perhaps copy-paste the lines starting with `+` to the new branch, while paying attention to any changes others might have made to those lines.

Would that work? If not, we can perhaps resolve all the conflicts together on a call.

**Comment by jpmckinney** [comment]
Actually, the merge is not that bad. I will do it like for #1208.

**Comment by jpmckinney** [comment]
Notes on the merge:

* The description of record was changed at `records_reference.md` but not in `record-package-schema.json`. I changed it in both places to be aligned. (More below.)
* In related_processes.md, I removed "initiation" from "multiple initiation stages".

The description of a record had changed in #1307. For this PR, I merged it as:

> Information about a contracting process, a planning process, or a single stage of a multi-stage procedure (e.g. a framework agreement with reopening of competition).
>
> There should be a single record per process per [distribution](https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution), where a distribution might be a specific API endpoint or a specific bulk download file.

The new wording is a bit different on `records_reference.md`.

In this PR, it was previously:

> Information about a contracting process or a contracting planning process. Furthermore, a record may also inform about a single stage of a multi-stage procedure (e.g. a framework agreement with reopening of competition).

**Comment by jpmckinney** [comment]
Since we now have planning processes and contracting processes, I changed occurrences of "contracting process identifiers" to be either "process identifiers" or "open contracting process identifiers" (where "open contracting" modifies "process identifiers") in a new commit.

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
@JachymHercher I did my review as commits. Each commit is fairly "atomic" so you should be able to click on each of them to see a reasonable "diff" (excluding the merge commits).

@yolile Since this is the most significant clarification/change in 1.2, please also review.

Besides the image, I think any outstanding issues can be fixed as follow-up issues to #866.

**Comment by JachymHercher** [comment]
@jpmckinney, thank you for the review. I've gone through your commits and have no major comments. Minor ones: 

____

> Information about a contracting process or a contracting planning process. Furthermore, a record may also inform about a single stage of a multi-stage procedure (e.g. a framework agreement with reopening of competition).

The reasoning behind this wording was that ocid identifying a "single stage of a multi-stage procedure" is a bit of a hack, so it's included as an "afterthought". 

(The existing wording also removes any need for the "minor drafting changes" mentioned at https://github.com/open-contracting/standard/issues/866#issuecomment-889808083.) 
____ 

In https://github.com/open-contracting/standard/pull/1216/commits/9943e8bcc8d5756cbfbc6f226e4ec7cd4c4bbe29#diff-ad7a21639d13433e0d0f06126a4ce0f979ab8e86ed7f6a28a439df33458419c9, you simplified the note on planning/contracting processes (which looks better now), including the removal of a link to a GitHub issue discussing the matter. Are you sure you don't want to keep the GitHub link? I think the approach of linking "loose ends" in OCDS to GitHub issues is quite nice/useful, but I understand there might also be reasons not to do it.

___ 

In https://github.com/open-contracting/standard/pull/1216/commits/257a27983f73280b0161bf1b79d4086f19d9d6b2#diff-6ab9cecd6acf675b41026bf29c8ed24c2779a9824cc7d09f9ea78b3e73036faf, you removed the following note:

> OCID is primarily an identifier for an OCDS contracting process. However, in OCDS 1.2 and earlier, it is [also used as an identifier for planning processes and single stages of multiple stage procedures](../guidance/map/unsuccessful_processes). For a future, backwards incompatible version of the standard introducing a separate identifier for contracting planning processes and publishing data on multiple stage procedures under one OCID is being considered ([GitHub issue](https://github.com/open-contracting/standard/issues/866)).

Given the clarification in https://github.com/open-contracting/standard/issues/866#issuecomment-889808083, I understand why you remove the mention of " introducing a separate identifier for contracting planning processes". However, wouldn't it be useful to keep the note there, even if the sentence only refers to "publishing data on multiple stage procedures under one OCID is being considered "? Same as above, I like highlighthing loose ends, hinting at future developments, showing people where to give their opinion.

**Comment by yolile** [comment]
> @yolile Since this is the most significant clarification/change in 1.2, please also review.

It looks good for me, but should we also update, after merging this, the unsuccessful tender example to have 1 ocid for the planning stage, then another one for the unsuccessful tender, and finally a third one for the successful tender? And, here, for the third ocid, are we going to have two entries in the related process array, one for the unsuccessful tender and another one for the planning stage?

And, should we also update all the other JSON/worked examples where the planning stage is used?

**Comment by jpmckinney** [comment]
I'll restore the "Furthermore" construction, as mentioned in my recent comments in #866.

In terms of loose ends:

* The challenges/hacks for representing multi-stage procedures in OCDS 1.x is a major issue, so it is important to direct people to an issue where they can contribute (and to demonstrate that we are aware of and working on the issue). I retained the box with the link to #440 on `contracting_planning_processes.md`. I'll think about linking to it from `identifiers.md` (#866 is more about our current hack for fixing 440, so I'd rather link to 440).
* Whether to separate planning and contracting processes is one of many decisions that have to be made in OCDS 2.0. #866 is not the best place for that discussion, because it is stuck with OCDS 1.1 concerns. It's fine to link to issues about OCDS 1.x in the OCDS 1.x documentation, but since OCDS 2.0 could (in theory) be an entirely different standard, it's less appropriate. We don't want to start conversations about OCDS 2.0 with the baggage/mindset of OCDS 1.x.

I think those are the only two loose ends; both appeared on both contracting_planning_processes.md and identifiers.md.

I have a longer comment about identifying planning processes in #866, but there is no action for now.

**Comment by jpmckinney** [comment]
> > @yolile Since this is the most significant clarification/change in 1.2, please also review.
> 
> It looks good for me, but should we also update, after merging this, the unsuccessful tender example to have 1 ocid for the planning stage, then another one for the unsuccessful tender, and finally a third one for the successful tender? And, here, for the third ocid, are we going to have two entries in the related process array, one for the unsuccessful tender and another one for the planning stage?
> 
> And, should we also update all the other JSON/worked examples where the planning stage is used?

I think we should do all those things. Is it alright, in your opinion, to do those as a high-priority follow-up issue?

For updating the unsuccessful tender example, I think it's fine for the related processes to just be a chain, e.g. the final process only links to the previous attempt, which in turn only links to the planning process. That said, I don't think it's incorrect for the final process to also link to the planning process.

**Comment by yolile** [comment]
> I think we should do all those things. Is it alright, in your opinion, to do those as a high-priority follow-up issue?

Not a high priority, just something we need to remember to do

**Review by yolile — APPROVED** [review]

**Comment by jpmckinney** [comment]
Follow-up issue is #1362. The problematic commit in my review was 257a27983f73280b0161bf1b79d4086f19d9d6b2

I have edited `ocid`. The original in this PR:

> A globally unique identifier for this OCDS contracting process. Furthermore, this identifier can also refer to an OCDS planning process or a single stage of a multiple stage procedure.

Now:

> A globally unique identifier for the contracting process that the release describes. Alternatively, this identifier can refer to a planning process or a single stage of a multiple stage procedure.

Since this is the release schema, this version more clearly communicates the relationship between a release and contracting process. I also use "Alternatively" instead of "Furthermore" to make clear that these are alternatives: i.e., that a contracting process and planning process are different types of things.

You can read my lengthy commit message for 4abc3af

**Comment by jpmckinney** [comment]
In the merge commit, I had changed the description of record. The original version in this PR was:

> Information about a contracting process or a contracting planning process. Furthermore, a record may also inform about a single stage of a multi-stage procedure (e.g. a framework agreement with reopening of competition).

This unnecessarily replicates semantics that should be deferred to a release. It is now:

> A record aggregates releases with the same open contracting process identifier (ocid).

**Comment by yolile** [comment]
I guess another follow-up is to address this comment: https://github.com/open-contracting/standard/pull/1335/files#r670825255 by updating the planning definition and fields.

**Comment by jpmckinney** [comment]
> I guess another follow-up is to address this comment: https://github.com/open-contracting/standard/pull/1335/files#r670825255 by updating the planning definition and fields.

Thankfully, that PR is still open :)

**Comment by jpmckinney** [comment]
🚀 🚢 :shipit:

**Pull request merged**
