### PR TITLE
Correct typos

### PR DESCRIPTION
**Pull request by jpmckinney**
To avoid another bugfix release in quick succession, I ran aspell over the repository using this command:

`find . -type f -not -path '*/\.*' -not -path '*/docson/*' -not -name '*.css' -not -name '*.html' -not -name '*.js' -not -name '*.png' -not -name '*.po' -not -name '*.py' -not -name '*.sh' -not -name '*.svg' -not -name '*.txt' -exec aspell -H check '{}' ';'`

This pull request doesn't update all the `*.po` files. Is there documentation somewhere on how those are regenerated when the English source is changed?

More significant corrections are:

1. I noticed a few cases where `openCodelist` was full lowercase (`opencodelist`). I don't know if this has a more serious impact than the other typos.
1. The code `illlustration` has too many L's, but I was also wondering whether it was intended to be `illustrations` (plural) since the other codes in that list are plural.

I noticed a few issues that I didn't correct:

1. It's perhaps a little confusing for the documentation to use British spelling but the schema to (mainly) use American spelling (like favoring 's' to 'z' especially where the documentation uses 'organisation' but the fields use 'organization').
1. We also seem to be inconsistent with:
    * 'OCID', 'ocid' (I might prefer using lowercase everywhere to avoid suggesting uppercase being correct in JSON files)
    * 'metadata', 'meta-data'
    * 'codelist', 'code-list', 'code list'
    * 'changelog', 'change-log', 'change log'
    * 'datapackage', 'data package'
    * 'amongst', 'amoungst', 'among'

I can of course make fewer typo corrections (e.g. maybe focus on the typos in JSON and CSV files) or split the PR into pieces if that makes sense.

I can also share my aspell configuration files if anyone wants to repeat this exercise in the future (the config files add a bunch of words to the dictionary).

### CODE REVIEW

**Comment by jpmckinney** [comment]
I can also make the spelling consistent with American English, and use 'codelist' consistently (per [style guide](http://crm.open-contracting.org/projects/ocds/wiki/Style_Guide)), but maybe in a separate pull request to make it simpler.

**Comment by timgdavies** [comment]
If you can hold off on that just until I've finished going through the direct typo comments from the French translation - then we might want to re-run the aspell  process.

**Comment by Bjwebb** [comment]
> This pull request doesn't update all the *.po files. Is there documentation somewhere on how those are regenerated when the English source is changed?

https://github.com/open-contracting/standard#translations

**Comment by jpmckinney** [comment]
@Bjwebb Thanks! I'll update the `.po` files after I get the signal from @timgdavies to proceed with commits to this PR.

**Comment by timgdavies** [comment]
#502 should now be ready for this.

If you can split into three blocks:

* JSON files
* CSV files
* Markdown files

that would be super handy. 

If you can also document the process in the CRM wiki (with the relevant aspell configuration) then I'll try and get this added to my workflow as well.

**Comment by jpmckinney** [comment]
Sounds good!

* I assume I should wait for #502 to merge and then rebase/restart?
* Re: three blocks, do you mean one commit per block, or one PR per block?
* In the wiki, I'd add a link under ["Standard maintenance"](http://crm.open-contracting.org/projects/ocds/wiki#Standard-maintenance)?

**Comment by timgdavies** [comment]
#502 might not be merged till Tuesday, but I think that should be alright. 

One commit per block would be fine. 

Wiki location sounds good :)

**Comment by jpmckinney** [comment]
Noting I can also correct 'two-digit ISO 639-1' to 'two-letter'.

Also, all other ISO references in the docs use no spaces (e.g. ISO8601), but ISO 639-1 sometimes has a space or a hyphen. I can remove the space while making the 'digit'/'letter' correction.

**Comment by timgdavies** [comment]
That correction and consistency clean-up on the ISO references would be great too,

**Comment by timgdavies** [comment]
Ready for this to run now if that works for you. I'm working on the changelog for #510

**Comment by jpmckinney** [comment]
@Bjwebb I'm not sure that documentation does what I need. For example, if I correct the casing of 'javascript' to 'JavaScript' in a source file like `standard/docs/en/schema/release.md`, I also want that to be corrected in the `.po` files. In Django, I can run `makemessages` and it will fuzzy match the English string. What do I do here to align the `.po` files with my changes?

**Comment by jpmckinney** [comment]
@timgdavies First bit of documentation at http://crm.open-contracting.org/projects/ocds/wiki/Spell_Checking I also updated the [style guide](http://crm.open-contracting.org/projects/ocds/wiki/Style_Guide) to prefer the whitespacing of 'changelog' and 'data package'. I'll split the commits as JSON, CSV, Markdown once I know how to align the `.po` files.

I didn't change to consistently using 'metadata' over 'meta-data', as 'meta-data' is used a lot and I wonder whether there is a reason for that?

Also, I didn't change any casing of OCID/ocid, although it is inconsistent. I might prefer always using lowercase.

**Review by timgdavies — COMMENTED** [review]
I've set the merge against 1.1.1 and resolved a small number of merge conflicts. 

I've reviewed the commits and happy that all edits make sense. 

I need to review the best approach on the .po files before merging - just to check on how this works with the transifex workflow.

**Comment by Bjwebb** [comment]
> I need to review the best approach on the .po files before merging - just to check on how this works with the transifex workflow.

`tx push -t --skip`  from the bottom of https://github.com/open-contracting/standard#translations - but beware that this will clobber any edits people have done on transifex since the last time it was pulled and commited.

**Comment by jpmckinney** [comment]
@Bjwebb Can you add these sorts of consequences to the readme?

**Comment by Bjwebb** [comment]
https://github.com/open-contracting/standard/commit/0ef2aa0bada3100f04bf8c1b434b8d5aa1144417

**Pull request merged**
