### PR TITLE
Fixed eligibilityCriteria description, added .tender.selectionCriteria

### LINKED ISSUE #901: Deprecate eligibilityCriteria and add exclusionGrounds
# Background

In OCDS, selection criteria (for example, the criteria used to qualify bidders in a selective procedure in the sense of the GPA) are often mapped to `eligibilityCriteria`.

However, selection criteria are not the same as eligibility criteria. For example, the [UNDP](https://www.undp.org/content/undp/en/home/procurement/business/qualifications.html) has qualified but ineligible bidders, e.g. due to suspension or debarment:

> … all vendors must be qualified, as well as eligible.

> Eligible vendors are qualified vendors that have not been temporarily suspended or debarred by UNDP or another UN agency, fund or programme.

`eligibilityCriteria` was added in #139, and is described as:

> A description of any eligibility criteria for potential suppliers.

At the time, `awardCriteria` was incorrectly termed `selectionCriteria`, which was fixed in #162; the confusion might have started in #140. 

# Proposal

An effective solution depends on how frequently `eligibilityCriteria` is used to disclose selection criteria (a very common concept in procurement) versus eligibility criteria (rare).

If the field is mainly used for selection criteria, then adding a new `selectionCriteria` field would create a situation in which there are two terms used to disclose the same concept.

If the field is rarely used, or only used for eligibility criteria, then we can add a new `selectionCriteria` field, and clearly explain the difference between the two.

We should also avoid the terms 'eligible' and 'eligibility' in all related guidance and extensions, unless that is actually what we mean.

### PR DESCRIPTION
**Pull request by ColinMaudry**
Waiting for usage data to determine whether `eligibilityCriteria` is broadly used for selection criteria.

Closes #901

### CODE REVIEW

**Comment by ColinMaudry** [comment]
What is this bit for? (I just cloned the one for `eligibilityCriteria`)

```json
"^(selectionCriteria_(((([A-Za-z]{2,3}(-([A-Za-z]{3}(-[A-Za-z]{3}){0,2}))?)|[A-Za-z]{4}|[A-Za-z]{5,8})(-([A-Za-z]{4}))?(-([A-Za-z]{2}|[0-9]{3}))?(-([A-Za-z0-9]{5,8}|[0-9][A-Za-z0-9]{3}))*(-([0-9A-WY-Za-wy-z](-[A-Za-z0-9]{2, 8})+))*(-(x(-[A-Za-z0-9]{1,8})+))?)|(x(-[A-Za-z0-9]{1,8})+)))$": {
          "type": [
            "string",
            "null"
          ]
        }
      }
```

**Comment by ColinMaudry** [comment]
My inspiration for selection criteria examples comes from this page: https://www.procurementjourney.scot/route-3/develop-documents/exclusion-selection-and-award-criteria/selection-criteria

**Comment by jpmckinney** [comment]
> What is this bit for? (I just cloned the one for `eligibilityCriteria`)

That's related to this feature: https://standard.open-contracting.org/latest/en/schema/reference/#language

However, #229 proposes eliminating that feature.

**Comment by jpmckinney** [comment]
> My inspiration for selection criteria examples comes from this page: https://www.procurementjourney.scot/route-3/develop-documents/exclusion-selection-and-award-criteria/selection-criteria

Nice, the page about exclusion criteria could also be inspiring for eligibility criteria: https://www.procurementjourney.scot/route-3/develop-documents/exclusion-selection-and-award-criteria/exclusion-criteria

**Review by jpmckinney — COMMENTED** [review]
Please update the changelog. Otherwise, looks good!

**Comment by ColinMaudry** [comment]
I added a new field (`Tender.selectionCriteria`), but `python util/make_versioned_release_schema.py` fails:

```
Traceback (most recent call last):
  File "util/make_versioned_release_schema.py", line 13, in <module>
    from conf import release  # noqa isort:skip
  File "/home/colin/git/standard-ocds/docs/conf.py", line 20, in <module>
    import standard_theme
ModuleNotFoundError: No module named 'standard_theme'
```

**Comment by jpmckinney** [comment]
When running locally? Have you done `pip install -r requirements.txt` for the standard repo?

**Comment by jpmckinney** [comment]
I'm closing this PR, as we need to discuss more in #901 and #1120.

**Pull request closed without merging**
