### PR TITLE
Update to latest version of documentation-support

### PR DESCRIPTION
**Pull request by jpmckinney**
Follow-up to #724, which it includes.

### CODE REVIEW

**Comment by jpmckinney** [comment]
I'm not sure why the three search tests are failing (same locally). Nothing that could impact search has changed…

**Comment by jpmckinney** [comment]
Hmmm:

> Failed to load resource: Origin http://0.0.0.0:8000 is not allowed by Access-Control-Allow-Origin. http://www.standard-search.default.opendataservices.uk0.bigv.io/v1/search?q=ocds&base_url=http%3A%2F%2F0.0.0.0%3A8000%2Fen%2F

> XMLHttpRequest cannot load http://www.standard-search.default.opendataservices.uk0.bigv.io/v1/search?q=ocds&base_url=http%3A%2F%2F0.0.0.0%3A8000%2Fen%2F due to access control checks.

**Comment by jpmckinney** [comment]
@kindly Could this have anything to do with recent work on search? cc @robredpath

**Comment by robredpath** [comment]
@jpmckinney yes, sorry - the search service had a bad upgrade yesterday and so we didn't have search for a few hours. We got it back online earlier today, and we've added additional monitoring to catch the failure that caused it.

**Comment by jpmckinney** [comment]
@robredpath Great to hear, thanks!

**Comment by jpmckinney** [comment]
These are just small tweaks to keep all docs repos using the same dependencies. Will merge once tests complete.

**Pull request merged**
