### PR TITLE
Clarify contracts description (896)

### LINKED ISSUE #896: Clarify Contract description
# Background

`contracts`:

> Information from the contract creation phase of the procurement process.

`Contract`:

> Information regarding the signed contract between the buyer and supplier(s).

The eProcurement Ontology (ePO) has a class for Contract:

> A voluntary, deliberate, and legally binding agreement between two or more competent parties.

The ePO has a class for Purchase Contract, which is [synonymous](https://github.com/eprocurementontology/eprocurementontology/issues/170) with: specific contract, call-off contract, draw-down contract (Ireland) and contract under a framework agreement. This concept also applies to "dynamic purchasing systems", which UNCITRAL considers synonymous with "open framework agreement".

# Discussion

None of these definitions clearly indicate which contracts between buyer and suppliers belong in the `contracts` array, which can include:

* A contract establishing the relationship, like the set-up of a framework agreement
* A contract within the relationship, like a call-off contract under a framework agreement
* Purchase orders ([the acceptance of a purchase order forms a legal contract](https://en.wikipedia.org/wiki/Purchase_order))
* Catalog purchases

## Framework agreements

The most important difference between the set-up contract and call-off contracts is that no goods or services are delivered directly under the set-up contract. The framework agreement has a maximum value, but no value in the same sense as a call-off contract. It might specify items to be delivered by call-off contracts, but these are not delivered directly under the set-up contract and might not have specific quantities.

The [present guidance](http://standard.open-contracting.org/latest/en/implementation/related_processes/) puts call-off contracts in the `contracts` array, and leaves the set-up contract in the `awards` array. This avoids confusion of the differences above, but it isn't perfect, as the set-up contract is indeed a contract itself. Some facts about the set-up contract might be better understood in the context of a contract than in the context of an award decision.

TED and eForms can inform this discussion.

## Purchase orders

In a contract with definite quantities of items, purchase orders are more of an implementation detail, describing the specific timing, quantities, deliveries, etc. of the items in the contract.

In this first case, purchase orders seem appropriate under `contracts.implementation`.

In a contract with indefinite quantities, and especially in a contract with multiple suppliers (e.g 'simultaneous supply' in Paraguay #888), a user will have to look at the purchase orders to determine the actual quantities delivered by which suppliers, and to determine the real value of the contract. This is closer, in form, to a framework agreement with call-off contracts.

In this second case, it seems, at first, more appropriate to follow the same model as framework agreements.

However, we might need to compromise on recommending just one model for all purchase orders, because it might be too difficult or confusing to try to explain these two scenarios, both of which use the term 'purchase order'. It might also be impossible for systems to distinguish which model is appropriate for a particular procurement.

If so, we should think through how to distinguish the two cases, where possible. For example, in the second case, perhaps the contract should have only a `maxValue` and not a `value`. This would be similar to how the set-up contract in a framework agreement would be modelled, if we developed guidance for how to do so in `contracts`.

## Catalog purchases

TBD

# Proposal

1. Update the definition of `contracts` and `Contract` to be more clear on the scope.
1. Review the properties of set-up contracts in TED and eForms and determine whether they make more sense on an Award or Contract in OCDS. If the latter, update the guidance. This can be done as part of #249 and would resolve #784.
1. See #897

### PR DESCRIPTION
**Pull request by JachymHercher**
#896 

together with #1216, addresses https://github.com/open-contracting/standard/issues/903

### CODE REVIEW

**Comment by jpmckinney** [comment]
@JachymHercher Please click "Ready for review" unless this PR is still in draft.

**Comment by JachymHercher** [comment]
I left it as a draft intentionally, because I haven't yet drafted the guidance section. I'm waiting for https://github.com/open-contracting/standard/pull/1123 with that (and perhaps I should wait also for getting started), see https://github.com/open-contracting/standard/issues/896#issuecomment-774772868.

**Comment by jpmckinney** [comment]
@JachymHercher #1123 is merged, and you've now seen the Primer, so I think this issue is now unblocked.

**Comment by JachymHercher** [comment]
Ready for review, see https://github.com/open-contracting/standard/issues/896#issuecomment-888948114

**Comment by jpmckinney** [comment]
Notes on the merge:

* Somehow, docs/guidance/map/awards_contracts_buyers_suppliers.md reappeared – possibly from a bad merge in #1356
* The changelog was getting quite messy, so I took the opportunity to put it in order

I also added a commit for a broken link, that I assume also occurred in #1356.

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
