### PR TITLE
build: Convert eval-rst directives

### PR DESCRIPTION
**Pull request by jpmckinney**
https://gist.github.com/jpmckinney/88c846651ab5411d1ed3a6fe222ce08f

### CODE REVIEW

**Comment by jpmckinney** [comment]
@choldgraf Based on #1221 I wrote the above script and compared the output. After running it (and many fixes), the output was the same (except for end-of-line whitespace, additional directives converted, etc.), plus one `.. markdown::` block where I had to manually convert RST syntax to Markdown. (I'll use the script on some of our smaller docs sites.)

**Comment by choldgraf** [comment]
Whoah nicely done 👍

**Comment by jpmckinney** [comment]
Now we can do the fun part of updating the theme 😄

**Comment by choldgraf** [comment]
haha indeed - much more enjoyable than programmatically removing eval-rst blocks.

**Pull request merged**
