### PR TITLE
Awards-related examples

### PR DESCRIPTION
**Pull request by duncandewhurst**
@jpmckinney tests are failing on `consortia_simple.csv` with the following errors, however I've checked the file using csvkit's `csvclean` command and it reports no errors, any ideas?

```
=================================== FAILURES ===================================

/tmp/test_csv.py:121: AssertionError: One or more codelist CSV files are invalid. See warnings below.

=============================== warnings summary ===============================

test_csv.py::test_valid

  ERROR: docs/examples/consortia_simple.csv has 5 not 8 columns in row 2

test_csv.py::test_valid

  ERROR: docs/examples/consortia_simple.csv is improperly formatted (e.g. missing trailing newline, extra quoting characters, non-"\n" line terminator):

  'awards/0/id,awards/0/title,awards/0/suppliers/0/name,awards/0/suppliers/0/identifier/scheme,awards/0/suppliers/0/identifier/scheme,awards/0/suppliers/1/name,awards/0/suppliers/0/identifier/scheme,awards/0/suppliers/0/identifier/scheme\nDHSC-2019-A18074,Medical imaging device development,SIEMENS PUBLIC LIMITED COMPANY,GB-COH,727817,MICROSOFT LIMITED,GB-COH,1624297\n'

  'awards/0/id,awards/0/title,awards/0/suppliers/0/name,awards/0/suppliers/0/identifier/scheme,awards/0/suppliers/0/identifier/scheme,awards/0/suppliers/1/name,awards/0/suppliers/0/identifier/scheme,awards/0/suppliers/0/identifier/scheme\nDHSC-2019-A18074,Medical imaging device development,SIEMENS PUBLIC LIMITED COMPANY,1624297,1624297,MICROSOFT LIMITED,1624297,1624297\n'
```

### CODE REVIEW

**Review by mrshll1001 — COMMENTED** [review]
Just had a quick review based on the content in the GDoc and the request in the CRM. Couldn't spot any errors. I don't know it would be failing builds, but the changes look like they implement the planned content fine.

**Comment by yolile** [comment]
@duncandewhurst added a comment in the google doc!

**Comment by duncandewhurst** [comment]
> @duncandewhurst added a comment in the google doc!

Thanks Yohanna - I've updated the PR now

**Comment by jpmckinney** [comment]
The problem is due to non-unique column headings (`scheme` instead of `id` and `0` instead of `1`). Easier to see here: https://github.com/open-contracting/standard/blob/3d40597/docs/examples/consortia_simple.csv

**Pull request merged**
