### PR TITLE
1.1 dev extension tables directives

### PR DESCRIPTION
**Pull request by edugomez**
This PR adds a new section _Using Extensions_ to _Extensions_ in 1.1 docs. The new section includes tables with community and core extensions that can be selected and added to the `extension` array in a chunk of json that the user can copy and add to their packages.   

The tables are created as a directive and translated (for `name` and `description`) as they are created, taking the translations from the extensions themselves (for both core and community ones) as suggested by @timgdavies. The thing is, most (all?) of the extension only have _'en'_ versions for those fields, which means that as it stands they will be shown in English for all languages.

### CODE REVIEW

**Review by timgdavies — APPROVED** [review]

**Comment by timgdavies** [comment]
The main change looks good. @bjwebb may be able to resolve the build_docs.sh issue

**Comment by edugomez** [comment]
@timgdavies, I spoke to @Bjwebb and he will take over from here, not only to fix the merge conflict but also a couple of additional issues.

**Comment by edugomez** [comment]
Screen shots for extension docs:

core_ext_select

**Comment by edugomez** [comment]
community_ext_select

**Comment by edugomez** [comment]
community_ext_table

**Pull request merged**
