### PR TITLE
Clarify uniqueness of release, award and contract identifiers

### LINKED ISSUE #455: Clarify the scope of uniqueness of Release ID
In OCDS 1.0 & 1.1 we define ```release.id``` as:

> "An identifier for this particular release of information. A release identifier must be unique within the scope of it’s related contracting process (defined by a common ocid), and unique within any release package it appears in. A release identifier must not contain the # character." 

However:

(a) This is conceptually subtle and difficult to communicate;
(b) As we see people starting to aggregate data from multiple sources, this creates a challenge, as an aggregator of information might end up with releases from multiple sources, which have distinct ```ocid``` values, but the same ```release.id```. Strictly then, the re-publisher would have to manipulate the release ids if it wanted to present both in the same package.

This leads to a suggestion from @edugomez that we should just make ```release.id``` globally unique. 

This would be simply enough for people to implement, using their OCDS prefix, and OCID. 

It would likely be a 2.0 issue.

### LINKED ISSUE #682: Correct the explanation of 'unique' with respect to release IDs and tender, award and contract IDs
http://standard.open-contracting.org/latest/en/schema/identifiers/

> The tender, award and contract IDs must be unique within the contracting process it is part of.

> For any given ocid, there should be no two tender, award or contract IDs that refer to different tender, award or contract sections respectively.

The second paragraph is confusing, because two (different) IDs can of course refer to two different sections.

The second paragraph either needs to be rephrased or removed.

Originally reported by @colinmaudry via Transifex.

### PR DESCRIPTION
**Pull request by jpmckinney**
closes #682, closes #455 

There is only one `tender/id` field, so I think it makes more sense to omit anything about the uniqueness of that field.

Another significant change is described in the changelog: Eliminate the conflicting rule that release identifiers must be unique within release packages. Uniqueness within the scope of a release package either implies that release identifiers must be globally unique, or imposes an arbitrary restriction on the contents of release packages, as there is no rule preventing release packages from containing releases from different contracting processes. Release identifiers are only required to be locally unique within the scope of a contracting process. The `ocid` and `id` values of a release can be used together to disambiguate releases within a release package.

### CODE REVIEW

**Comment by duncandewhurst** [comment]
I think the reason that global uniqueness for release identifiers was suggested in #455 is because the description of the `url` field in the linked releases part of the record schema is as follows:

> The URL of the release which contains the URL of the package with the releaseID appended using a fragment identifier e.g. http://standard.open-contracting.org/latest/en/examples/tender.json#ocds-213czf-000-00001

**Comment by jpmckinney** [comment]
Hmm, I think it's very likely that release IDs are not, in practice, globally unique, as that was never stated anywhere clearly, and can only be determined by following the implications of multiple disparate pieces of information. So, with respect to the suggestion in #455, I believe that making the rule that release IDs must be globally unique is not an acceptable resolution to the lack of clarity that this PR intends to resolve.

The only other mention I find of this way of identifying releases inside release packages is in `records_reference.md`: "In order to locate the specific release inside a release package the releaseID of the release should be appended to the package URL using a fragment identifier."

Rather than forcing release IDs to be globally unique, we can simply clarify that, if the `url` of a linked release matches multiple releases, then the `ocid` (which is required in the record package schema) must be used to disambiguate the releases.

If that's fine, I'll create an issue for 1.1.5 about that – as I think we should explore other solutions, like changing the URL pattern to not be ambiguous.

For 1.1.4, I think it's still important to clarify that release IDs need only be locally unique, as that is the practice and what I consider to be the intention (it's not clear that the implication of global uniqueness was understood by the authors, as otherwise it would have been much simpler to simply say so, rather than have the complex combination of unclear statements that we have now).

**Comment by duncandewhurst** [comment]
Yes, that sounds good. Just flagging that those other references will need updating but I think it's fine to do that 1.1.5.

This reminded me why publishing releases in packages is a must (so that linked releases can be fetched in a consistent way) so I added a note to #605

**Review by duncandewhurst — APPROVED** [review]

**Comment by jpmckinney** [comment]
I created an issue about those references and set it to the 1.1.5 milestone #844

**Pull request merged**
