### PR TITLE
Adding API guidance 

### PR DESCRIPTION
**Pull request by odscrachel**
Adding API guidance agreed in CRM-7950

### CODE REVIEW

**Comment by jpmckinney** [comment]
@odscrachel I don't know if this is ready for review (need to request my review to make it clear).

There are four errors relating to links like `#heading=h.pw97dsu9qvtf`. Please update these to links like `#bulk-downloads`, etc. (i.e. the lowercase, hyphenated version of the heading on the page).

**Comment by odscrachel** [comment]
Thanks James, I've updated the headers and it's now ready to review

**Review by jpmckinney — APPROVED** [review]
I just had to fix some internal links in a new commit.

**Comment by yolile** [comment]
Hmm, I think this one should have been merged into `1.1-dev` instead, right?

**Pull request merged**
