### PR TITLE
Merge pagination extension

### LINKED ISSUE #1327: Merge the pagination extension
Creating a new issue for this comment from #928 since the main topic of that issue will be addressed separately:

> We should also look into merging in https://github.com/open-contracting-extensions/ocds_pagination_extension.

_Originally posted by @jpmckinney in https://github.com/open-contracting/standard/issues/928#issuecomment-660284323_

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes #1327

`api_responses.md` includes only the content from the pagination extension readme. I figure we can add more framing as part of #1084.

### CODE REVIEW

**Review by pindec — APPROVED** [review]

**Review by pindec — COMMENTED** [review]
Also may need to edit /docs/guidance/build.md "Establish your publication formats and access methods" section to remove the line "The OCDS pagination extension describes how to paginate OCDS data via an API."

**Comment by duncandewhurst** [comment]
Good spot! Thanks, @pindec.

**Comment by duncandewhurst** [comment]
@jpmckinney just flagging the outstanding review request, in case you missed it.

**Comment by jpmckinney** [comment]
Not forgotten, just backlogged.

**Comment by jpmckinney** [comment]
@duncandewhurst Ah, right, the reason I hadn't merged it originally was because I wasn't satisfied with the documentation of the pagination extension. We indeed revised it heavily as part of #1095, and that documentation now lives here: https://standard.open-contracting.org/staging/1.2-dev/en/guidance/build/hosting/#pagination

I think we can just remove the API responses page from this PR, change the link, and then review and merge.

**Comment by duncandewhurst** [comment]
Sounds good. I've made those changes so this PR is now ready for review.

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
