### PR TITLE
release-schema: Move Unit to definitions

### PR DESCRIPTION
**Pull request by yolile**
refs #1107

### CODE REVIEW

**Comment by jpmckinney** [comment]
Why is the description for the definition:

> A unit of measure for an item and its unit-price.

But for the field:

> A description of the unit in which the supplies, services or works are provided (e.g. hours, kilograms) and the unit-price.

Any reason not to re-use the field description?

**Comment by yolile** [comment]
@jpmckinney I wasn't sure if they need to be different or not. Should we keep them the same then?

**Comment by jpmckinney** [comment]
I think OK to make identical.

**Comment by yolile** [comment]
@jpmckinney done

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
