### PR TITLE
Images convention

### PR DESCRIPTION
**Pull request by yolile**
- Apply conventions introduced in https://github.com/open-contracting/standard-development-handbook/pull/258
- Include the upgrade_process image in Spanish
- Remove unused images

### CODE REVIEW

**Comment by yolile** [comment]
It could be faster to also update the `po` files as part of this PR

**Comment by jpmckinney** [comment]
> It could be faster to also update the `po` files as part of this PR

Agreed - I often update PO files when it's non-content-related.

**Comment by jpmckinney** [comment]
Looks good - I haven't reviewed carefully, as the renaming is an improvement, and Sphinx will complain if any image URLs are broken :)

**Comment by yolile** [comment]
Ok, so I pulled the recent changes from transifex, updated the `po` files, and pushed them to Tranfisex already too.

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
I'll trust the tests on this one :)

**Pull request merged**
