### PR TITLE
Check for duplicate keys in the schema

### PR DESCRIPTION
**Pull request by Bjwebb**
Creating a PR so I can find this again.

Tests fail because 1.1-dev branch fails.

@timgdavies I think you're planning to do some work on the 1.1-dev branch (updating your script, so that release-schema.json is correct) before we merge this, so assigning to you to ping me once that's done, and I can rebase.

### CODE REVIEW

**Comment by timgdavies** [comment]
I think the issue here was not that release-schema.json was wrong, but that I'd not run the:

````
cd standard/schema/utils
./make_validation_schema.py
````

stage. 

I think that script might need some attention anyway with the upgrade, as it looks like it has some custom handling for organisations etc. that we need to be aware of. 

However, for now I've run ```make_validation_schema.py``` and then pushed an updated commit that passes the tests.

**Comment by Bjwebb** [comment]
The lack of validation schema is why the tests were failing.

However, release-schema.json is missing this update https://github.com/open-contracting/standard/commit/18c80d3dd787ba3b1077aeb6b3ffdff3f283c16b

**Comment by Bjwebb** [comment]
Additionally, I think the work that needs to be done to update that script is in this pull request https://github.com/open-contracting/standard/pull/412 (so done, just waiting to be reviewed and merged).

**Comment by Bjwebb** [comment]
I've rebased this, and I think its now ready to merge, to make sure this test gets run for future schema changes.

**Review by timgdavies — COMMENTED** [review]
Looks good to me. Merge when ready.

**Pull request merged**
