### PR TITLE
Pull French translations from transifex

### PR DESCRIPTION
**Pull request by Bjwebb**
http://standard.open-contracting.org/1.1-dev-fr/fr/

### CODE REVIEW

**Comment by Bjwebb** [comment]
There's some broken markdown:
http://standard.open-contracting.org/1.1-dev-fr/fr/schema/merging/
http://standard.open-contracting.org/1.1-dev-fr/fr/implementation/related_processes/
http://standard.open-contracting.org/1.1-dev-fr/fr/implementation/amendments/
http://standard.open-contracting.org/1.1-dev-fr/fr/extensions/milestone_documents/
http://standard.open-contracting.org/1.1-dev-fr/fr/extensions/process_title/

**Comment by Bjwebb** [comment]
Here's a full list from running:

```sh
find build/fr | grep '\.html$' | xargs grep -E --color=always '(\] +\()|\*\*' | aha
```

https://pste.eu/p/RuUu.html

Here's the English for comparison: https://pste.eu/p/2hxJ.html

**Comment by timgdavies** [comment]
Thanks @bjwebb. I've run through on Transifex and I think I've fixed all of these. Can you re-check tomorrow.

**Comment by Bjwebb** [comment]
There were a couple missed, but I've fixed those.

**Pull request merged**
