### PR TITLE
record_package_schema: fix record definition letter case

### LINKED ISSUE #641: Fix letter case of schema definitions
Change the case of the `record` definition in `record-package-schema.json` to `Record`.

(Noting that, among properties, `former_value` doesn't follow the lowerCamelCase pattern, but it's deprecated anyhow.)

### PR DESCRIPTION
**Pull request by yolile**
closes #641

### CODE REVIEW

**Comment by yolile** [comment]
hmm now the test is failing due to:

>   schema/record-package-schema.json includes "object" in "items/type" at /definitions/Record/properties/releases/oneOf/0/items

This is because linked releases. Should I move linked releases to record package schema definition as well?

**Comment by jpmckinney** [comment]
In `records_reference` there's `:pointer: /definitions/record/properties/releases/oneOf/0/items` which needs to be updated. 

Otherwise, for the lint error, we can either copy the exception that was there for `record`, or we can moved linked release to a definition to `$ref`erence.

**Comment by yolile** [comment]
> or we can moved linked release to a definition to $reference.

I will move the linked release object to a definition in the record_package_schema

**Comment by jpmckinney** [comment]
@yolile I added a commit, because we try to avoid referencing the JSON type in field descriptions. While fixing that for `LinkedRelease` I noticed a few related descriptions I could tidy.

**Comment by yolile** [comment]
@jpmckinney looks good! should we include the descriptions updates in the changelog as well?

**Comment by jpmckinney** [comment]
Good catch! I added a commit.

**Comment by yolile** [comment]
@jpmckinney perfect, in that case, do you want to approve this or should I merge it directly?

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
