### PR TITLE
Add guidance about recommended extensions.

### PR DESCRIPTION
**Pull request by duncandewhurst**
From a [comment](https://docs.google.com/document/d/1JQCOQzLvwEeue6yE4AugyPXQlsC08-ljfUoBwJ4bNWQ/edit?disco=AAAAP-1SRPA) in the draft guidance from https://github.com/open-contracting/extension-explorer/issues/47

### CODE REVIEW

**Comment by jpmckinney** [comment]
"Recommended" currently has that correlation to the governance process, but it will not necessarily, going forward.

"Recommended" doesn't mean much more than that we encourage their use.

**Comment by duncandewhurst** [comment]
> "Recommended" doesn't mean much more than that we encourage their use.

We should clarify that somewhere, at least for the benefit of helpdesk analysts.

**Comment by jpmckinney** [comment]
Happy for suggestions as to where to clarify :)

**Comment by duncandewhurst** [comment]
We could just reword the proposed sentence as:

> You are encouraged to consider whether you can use extensions tagged as **Recommended** in the Extension Explorer.

**Comment by jpmckinney** [comment]
Sounds good. I think a simpler construction is:

> You are encouraged to consider using the extensions tagged as *Recommended* in the Extension Explorer.

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
