### PR TITLE
Add missing properties

### PR DESCRIPTION
**Pull request by duncandewhurst**
Addresses https://github.com/open-contracting/standard/issues/677

@timgdavies please could you check you're happy with the description for `record`

### CODE REVIEW

**Comment by jpmckinney** [comment]
Are records only published when a process is complete? If not, then a record won't provide "all the OCDS releases relating to a single contracting process" until that process is completed. We can perhaps add a clause to account for that temporal issue.

Also, are the MUST and SHOULD statements already part of the documentation, or are those new normative statements? I know they reflect our intention, but I just want to check that they have precedence.

**Comment by duncandewhurst** [comment]
> Are records only published when a process is complete? If not, then a record won't provide "all the OCDS releases relating to a single contracting process" until that process is completed. We can perhaps add a clause to account for that temporal issue.

No we expect a record to be published when the first release about a contracting process is published and to be updated throughout the process. I updated the description to read "all the existing OCDS releases"

> Also, are the MUST and SHOULD statements already part of the documentation, or are those new normative statements? I know they reflect our intention, but I just want to check that they have precedence.

Yes, these are on the [record reference](http://standard.open-contracting.org/latest/en/schema/records_reference/#versioned-release) page of the docs.

**Comment by jpmckinney** [comment]
PR looks good to me, then!

**Review by timgdavies — APPROVED** [review]
The definition works well.

**Pull request merged**
