### PR TITLE
Fetch markdown files from v1.1.1 READMEs of core extensions

### PR DESCRIPTION
**Pull request by Bjwebb**
- [x] Create metadata section
- [x] Check that the built docs look okay

TODO after merge:
- [x] Document script in the standard development handbook

### CODE REVIEW

**Comment by jpmckinney** [comment]
@Bjwebb Is there a script that does this? I can't seem to remember seeing relevant documentation.

**Comment by Bjwebb** [comment]
I think this was previously manual.

I've started writing a script for this pull request https://github.com/open-contracting/standard/pull/550/files#diff-938ec24ad4e51596153df9258530240f, but it looks like there's some extra work to do to create the Metadata section.

**Comment by jpmckinney** [comment]
Ah, I missed it. Can we add that script to the upgrade workflow documentation? https://github.com/open-contracting/standard-development-handbook/issues/4

**Comment by Bjwebb** [comment]
I think this is now ready for merge, could @timgdavies and/or @duncandewhurst double check?

The one thing I don't like is the TODO sections are pulled in, but I think this is preferable to being out of sync with the extension repos.

**Review by duncandewhurst — CHANGES_REQUESTED** [review]
Changes to the markdown files for the extensions look good, but noting that the links to the individual extension pages on http://standard.open-contracting.org/extensions-1.1.1-md/en/extensions/#core-extensions are set up to point to the /1.1/ build of the docs, rather than the build the user is browsing

**Comment by Bjwebb** [comment]
@duncandewhurst Looks like that's not a new issue, so I'm not sure this pull request is the best place to fix it. The current behaviour is what it is because the url comes from the extension registry (e.g. https://github.com/open-contracting/extension_registry/blob/v1.1.1/bids/extension.json#L3).

**Review by duncandewhurst — APPROVED** [review]

**Pull request merged**
