### PR TITLE
Add examples for framework agreements

### PR DESCRIPTION
**Pull request by jpmckinney**
Making in a PR so that I can review.

### CODE REVIEW

**Comment by jpmckinney** [comment]
This might need significant changes, depending on how #440 is resolved (see latest comment there).

**Comment by yolile** [comment]
Some comments from discussions/retreat;

- It is preferable to always use a new process for each call off even if it is a direct call off without competition and then, for direct call offs:
  * Add an `Award` object to `awards` and a `Contract` object to `contracts`
  * Set `awards.id` and `contracts.id` to the same value
  * Populate the `awards.value`, `awards.contractPeriod` and `awards.items` fields with the initial contract value, period and items respectively
  * If the contract value, period or items are subsequently updated, populate the `contracts.value`, `contracts.period` and `contracts.items` fields with the updated value

- We need a field to distinguish the FA tender from the traditional ones: we can use the techniques extension https://github.com/open-contracting-extensions/ocds_techniques_extension
- We need a field to distinguish the mini competition tenders from the direct call offs: the direct call offs are going to be modeled as a new process without the tender block.
- FA duration: the duration is mappend in the tender.contractPeriod field
- To map all the buyers who participate in the FA dont map the buyer object but include multiples parties with 'buyer' role
- For indicate who buyer is buying what, as each call off is a new process, use the buyer object in that new process.
- As each mini competition or call of is a new process, use the planning block to indicate the budget for that purchase.


cc @jpmckinney

**Comment by jpmckinney** [comment]
@yolile: Can you work with @duncandewhurst next week to rewrite this page based on the discussion at the retreat?

**Comment by jpmckinney** [comment]
Closing this PR as I think the updates will be easier to review as a new PR.

I assume @yolile's notes from the retreat will all be reflected in the new PR. If not, please create/update an issue with any outstanding notes.

**Pull request closed without merging**
