### PR TITLE
Primer 0.1

### LINKED ISSUE #614: Reword use cases page
The 'use cases' on this page are more like 'goals'. http://standard.open-contracting.org/latest/en/getting_started/use_cases/ My understanding of nomenclature is:

* goal: 'Value for money'
* outcome: Related to the goal of value for money, my desired outcome is 'More bidders per process', as my hypothesis is that more competition leads to lower cost to government.
* indicator: I design a methodology for periodically measuring progress against that outcome, e.g. number of bidders per process at time X compared to time Y, scoping to, e.g., procurement of medication. The same indicator may be relevant to multiple outcomes and goals.
* use case: A specific instance of using data to achieve an outcome in pursuit of a goal, which may involve the measurement of an indicator. It may be possible to generalize a use case beyond the specific context in which it was recorded.
* requirement: The specific needs to satisfy the use case, which may be needs for data, information, publication patterns, stakeholder engagement, etc.
* user need: Same as 'requirement'.
* user focus: An attention to users, which in the context of this discussion may simply mean attention to the cases where users can use OCDS to achieve outcomes in pursuit of goals.

See internal comment about this page: https://crm.open-contracting.org/issues/2217#note-21

### LINKED ISSUE #1239: Draft Primer to replace Getting Started section of documentation
As discussed, we've been working on a replacement to the current format for the Getting Started section of the documentation. To do that, I've drafted a series of pages that together form a "Primer." The primer will be organized around answering four main questions, with each having their own section within the primer, plus a landing page for the Primer to provide general orientation for users to the purpose of the primer.

What is OCDS?
How does OCDS work?
What does OCDS data look like? 
How can I implement OCDS?

Within each page, there will be a standard structure and order of elements: objectives, video inset, detail on key concepts, and further resources (OCDS documentation pages and other OCP materials).

### PR DESCRIPTION
**Pull request by EricReese15**
Fully updated primer based on user and Helpdesk feedback 

closes #1239, closes #614

### CODE REVIEW

**Comment by jpmckinney** [comment]
We need to decide what (if anything) to retain from these pages (if retained, need to add to Guidance):

* https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/
  * This is covered in the reference section (schema/reference) and some is covered on primer/how, though maybe some examples could be retained.
* https://standard.open-contracting.org/1.1/en/getting_started/releases_and_records/
  * This is largely covered by primer/releases_and_records, though maybe some examples could be retained. I think "easy releases" and other pages from #997 might cover the rest, but I'm not sure. The animation, I think, is not easily understandable outside helpdesk analysts who are familiar with the "block" visualization.

@yolile What do you think?

I'm not sure if/where to re-integrate the OCDS example:

````md
```{jsoninclude} ../examples/contract.json
:jsonpointer: /releases
:expand: releases, tender, awards, contracts, period, value, items, tag, parties, documents
```
````

**Comment by jpmckinney** [comment]
Preview should be available here if build succeeds: https://standard.open-contracting.org/staging/primer_0.1/en/primer/

**Comment by yolile** [comment]
For https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/:
- We can move https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/#codelists worked example to the map section, where the other worked examples are
- https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/#extensions This is already covered by the specific Extensions page
- https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/#building-blocks-fields could be preserved in https://standard.open-contracting.org/staging/primer_0.1/en/primer/how/#how-does-the-ocds-work after _"When mapping your data to the OCDS our sing OCDS data, you will encounter a number of common data fields and structures, which are described by the schema.. "_ section

For https://standard.open-contracting.org/1.1/en/getting_started/releases_and_records/:
- We have a complete video with examples now, so I'm ok with removing the animation. 
- https://standard.open-contracting.org/staging/primer_0.1/en/primer/releases_and_records/ doesn't mention packages and their metadata at all is that on purpose?
- I think that the releases and records examples that are part of https://standard.open-contracting.org/1.1/en/getting_started/releases_and_records/ are useful and not covered anywhere else, so we might want to keep them

**Comment by jpmckinney** [comment]
Thanks! I’ll move those to new pages. Can you review the rest of the PR in the meantime?

**Comment by yolile** [comment]
> Can you review the ready of the PR in the meantime?

Sure, I will!

**Comment by jpmckinney** [comment]
> For https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/:
> 
> * We can move https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/#codelists worked example to the map section, where the other worked examples are

I don't think this example does much more than the example in https://www.open-contracting.org/resources/ocds-1-1-codelist-mapping-template-guidance/, which is what we want people to use for mapping codelists. What do you think?

> * https://standard.open-contracting.org/1.1/en/getting_started/building_blocks/#building-blocks-fields could be preserved in https://standard.open-contracting.org/staging/primer_0.1/en/primer/how/#how-does-the-ocds-work after _"When mapping your data to the OCDS our sing OCDS data, you will encounter a number of common data fields and structures, which are described by the schema.. "_ section

When preparing the Primer, Eric and I were not sure that the metaphor of "building blocks" was actually very helpful.

* We might not preserve common definitions for items, etc., because extending them can have unintended consequences #606, in which case we will not have "building blocks" in the same way.
* It's not clear that it is especially relevant for an implementer to learn that some objects follow the same schema in different parts of the data. It seems okay to learn this in the schema reference.
* I created #1347 about changing the terminology.

So, I'm okay with not having this section. What do you think?

I'll create an issue to add example data to the schema reference, since that is the main benefit of this section. #1348

> For https://standard.open-contracting.org/1.1/en/getting_started/releases_and_records/:
> 
> * https://standard.open-contracting.org/staging/primer_0.1/en/primer/releases_and_records/ doesn't mention packages and their metadata at all is that on purpose?

The old page says very little about packages (only mentioning the `uri` metadata). Since packages are going to become optional #1084, it is not important to mention them in the Primer.

> * I think that the releases and records examples that are part of https://standard.open-contracting.org/1.1/en/getting_started/releases_and_records/ are useful and not covered anywhere else, so we might want to keep them

Do you mean the two Example and Hint boxes? Isn't the Example covered by: https://standard.open-contracting.org/1.1/en/guidance/build/change_history/

For the Hint, it is a useful demonstration of the value of compiled releases. However, we know that publishers are unlikely to correctly implement the merging behavior (it's quite easy to have bugs), and we know that very few publishers offer compiled releases anyway (unless they do "easy releases"). So, I think we've accepted that the registry is the way for users to access compiled releases.

**Comment by yolile** [comment]
> I don't think this example does much more than the example in https://www.open-contracting.org/resources/ocds-1-1-codelist-mapping-template-guidance/, which is what we want people to use for mapping codelists. What do you think?

True, I found this [mapping a local codelist worked example outline](https://docs.google.com/document/d/1e2V62fLBHoqcIdhdK4g3qTGq30onNmGnc9XK7i-mgUc/edit#heading=h.n0oaaum8p8f2), which means that at some point we thought that it would be useful to have that worked example, I guess. (see also the worked examples [spreadseet](https://docs.google.com/spreadsheets/d/1CclI28-fa2pPIMjckKjexZVkbn5rSgzVi1-1PZ_zsWc/edit#gid=0))

> It's not clear that it is especially relevant for an implementer to learn that some objects follow the same schema in different parts of the data. It seems okay to learn this in the schema reference.

Yes, actually, I think that it is more relevant for them to learn about that while developing an extension, for example, which is something more advance and requires understanding/looking at the schema reference, so I'm ok with not having this section too. (fun fact: I've never managed to found a correct/nice/perfect translation for this in Spanish, so I'm happy in that sense too)

> Since packages are going to become optional #1084, it is not important to mention them in the Primer.

That is what I thought, all good then.

> Do you mean the two Example and Hint boxes? Isn't the Example covered by: https://standard.open-contracting.org/1.1/en/guidance/build/change_history/

It is partially covered, the https://standard.open-contracting.org/1.1/en/getting_started/releases_and_records/#repeating-previous-information section is not covered and I think that it contains useful guidance about **minimal updates** (recently one data user referenced this section of the documentation, so at least it is useful for some people)
And for compile releases and easy releases, maybe we can add a reference to the easy releases guidance in https://standard.open-contracting.org/1.1/en/guidance/build/change_history/?

**Comment by jpmckinney** [comment]
Agreed on a call to:

* Update the codelist mapping template guidance with a better example, rather than have guidance in both the template's guidance and in the docs. Tracked in CRM-7491
* Create an issue to re-introduce a worked example for minimal updates and change history #1364

And in this PR, to:

* Link to easy_releases from change_history, for guidance on setting the release `id` 2d0b9c6a

**Pull request merged**
